name: Docker Setup Compose
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pwd;tree
      - name: "compose config"
        run: docker compose config
